### ISSUE TITLE
Adding CI 

### ISSUE THREAD

**Issue by CGMossa** [extendr/libR-sys#10]
We need to decide on which CI to use going forward.

I'd suggest we follow rOpenSci, and establish CI/CD using GitHub Actions (GHA), see [this](https://ropensci.org/technotes/2020/11/19/moving-away-travis/).

What do you all think? I'll update the final decision to be written here: **GitHub Actions**

In the meantime, here's an update to `PATH` variable on Windows from `cmd`, that we might need to configure things:

> ```
> install:
>   - cmd: set PATH=C:/R/R-4.0.2/bin/x64;%USERPROFILE%\scoop\apps\msys2\current\mingw64\bin;%USERPROFILE%\scoop\apps\msys2\current\usr\bin;%PATH%
> ```

**Comment by clauswilke** [comment]
Yes, GitHub Actions are a good choice. It makes sense to start with one platform (e.g. Linux, which is probably the easiest) and once that works add other platforms into the build matrix.

For R package testing, several Action templates are maintained by RStudio here: https://github.com/r-lib/actions

**Comment by CGMossa** [comment]
Excellent, I don't know how to proceed, but I'll tinker with this later this week.

**Comment by clauswilke** [comment]
To set up github actions, you just need to drop `.yaml` files into `.github/workflow` in any github repo. See e.g. here for rextendr: https://github.com/clauswilke/rextendr/blob/main/.github/workflows/R-CMD-check.yaml
(This uses prebuilt actions for R packages. I haven't tackled the Rust part yet.)

There are ready-made actions for rust here: https://actions-rs.github.io/ Unfortunately they don't tackle the libclang issue, as far as I can tell, so that'll require some fiddling on our part.

**Comment by clauswilke** [comment]
I have set up GH actions by copying over the working `.yml` file from extendr and applying a few minor fixes.

@andy-thomason Do you want to turn off Travis?

**Comment by andy-thomason** [comment]
With pleasure!
