### ISSUE TITLE
question: why keep the bindgen generated bindings in git?

### ISSUE THREAD

**Issue by ssh352** [extendr/libR-sys#216]
they could be auto generated from build.rs. Thanks!

**Comment by yutannihilation** [comment]
In my understanding, it's because the setup is too complex. As you can see, generating the bindings requires some extra setup (i.e., libclang). Considering this crate is used within an R package, the requirement is a bit too heavy for ordinary R users and package developers.

https://github.com/extendr/libR-sys#building-bindings-from-source-advanced
